---

- name: check vulnerability
  script: "{{ vulners[vulner] }} -d -n | grep 'vulnerable = ' | cut -d'*' -f2 | tr -d '\n'"
  register: vulner_info
  changed_when: false
  failed_when: false

- debug:
    msg: "vulnerable (0/1): {{ vulner_info.stdout }}"

# we assume only one vulnerability in the list for now
- name: set vulnerability facts
  set_fact:
    system_vulnerable: "{{ 'true' if (vulner_info.stdout == '1') else 'false' }}"
    system_vulner_list: "{{ [vulner] if (vulner_info.stdout == '1') else [] }}"